### ISSUE TITLE
issue while running example file.

### ISSUE THREAD

**Issue by ArzooShamoon** [UtaDaphniaLab/Gene_Annotation_Easy_Viewer#1]
I tried running example files in Windows, macOS, and Linux. The same error occurs in all three operating system.
<img width="1440" alt="Screenshot 2022-01-03 at 8 25 18 PM" src="https://user-images.githubusercontent.com/84401942/147945335-1e7fc424-53ee-404d-a292-4bcffbf0af39.png">

**Comment by TrungHuynh4** [comment]
This issue should be resolved with version 1.2.0.
